### ISSUE TITLE
Missing stress_mt, testlib should be named stress

### ISSUE THREAD

**Issue by mcuee** [libusb/libusb-cmake#8]
Reference:
https://github.com/libusb/libusb-cmake/blob/main/libusb/tests/Makefile.am

Currently `stress_mt` is not built. The excutable of `testlib` should be named as `stress` to be consistent with upstream libusb project.

**Comment by Youw** [comment]
do I understand correctly that `set_option` and `init_context` are separate tests as well?

**Comment by Youw** [comment]
It looks like `umockdev` is a test as well

**Comment by Youw** [comment]
Closing in favor of #10
